// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQTzkL4Fusfg-MHZWBDS8CA_k9Q1x17U',
    appId: '1:463117917591:web:d1606025902cd095a378d2',
    messagingSenderId: '463117917591',
    projectId: 'staffmanagmnt',
    authDomain: 'staffmanagmnt.firebaseapp.com',
    storageBucket: 'staffmanagmnt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgVKWItx8t3UUU7DS9kLfqe5ld-pDysA',
    appId: '1:463117917591:android:610724edcdf4bd4fa378d2',
    messagingSenderId: '463117917591',
    projectId: 'staffmanagmnt',
    storageBucket: 'staffmanagmnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWi93ZHF7wFI2PsUBjESL_pzus4TheJoM',
    appId: '1:463117917591:ios:731a0fc91eea0050a378d2',
    messagingSenderId: '463117917591',
    projectId: 'staffmanagmnt',
    storageBucket: 'staffmanagmnt.firebasestorage.app',
    iosBundleId: 'com.example.staffmngt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWi93ZHF7wFI2PsUBjESL_pzus4TheJoM',
    appId: '1:463117917591:ios:731a0fc91eea0050a378d2',
    messagingSenderId: '463117917591',
    projectId: 'staffmanagmnt',
    storageBucket: 'staffmanagmnt.firebasestorage.app',
    iosBundleId: 'com.example.staffmngt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUQTzkL4Fusfg-MHZWBDS8CA_k9Q1x17U',
    appId: '1:463117917591:web:5570f0db1ff2da80a378d2',
    messagingSenderId: '463117917591',
    projectId: 'staffmanagmnt',
    authDomain: 'staffmanagmnt.firebaseapp.com',
    storageBucket: 'staffmanagmnt.firebasestorage.app',
  );
}
